[package]
name = "mylaps-x2-rs"
version = "0.1.0"
authors = ["Skoky <skokys@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"

[build-dependencies]
bindgen = "0.53.1"
